version: "3"

vars:
  TAILWIND_CMD:
    sh: command -v tailwindcss >/dev/null 2>&1 && echo "tailwindcss" || echo "npx tailwindcss@latest"

tasks:
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:8080" --open-browser=false
  tailwind:
    desc: Watch Tailwind CSS changes
    cmds:
      - "{{.TAILWIND_CMD}} -i ./static/assets/css/input.css -o ./static/assets/css/output.min.css -m -w"
  go:
    desc: Run go server
    cmds:
      - air --build.cmd "go build -o tmp/bin/main" --build.bin "tmp/bin/main" --build.delay "100" --build.exclude_dir "node_modules,tmpo" --build.include_ext "go" --build.stop_on_error "false" --misc.clean_on_exit true

  sync_assets:
    desc: Sync assets to static folder
    cmds: 
      - air --build.cmd "go tool templ generate --notify-proxy" --build.bin "true" --build.delay "100" --build.exclude_dir "" --build.include_dir "assets" --build.include_ext "js,css" --build.stop_on_error "false" 
  dev:
    desc: Start development server with hot reload
    cmds:
      - concurrently --names "templ,tailwind,go_server,go_assets" --prefix "[{name}]" --prefix-colors "blue,magenta,green,cyan" "task templ" "task tailwind" "task go" "task sync_assets"
