version: "3"

vars:
  TAILWIND_CMD:
    sh: command -v tailwindcss >/dev/null 2>&1 && echo "tailwindcss" || echo "npx tailwindcss@latest"

tasks:
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go tool templ generate
  tailwind:
    desc: Watch Tailwind CSS changes
    cmds:
      - "{{.TAILWIND_CMD}} -i ./static/assets/css/input.css -o ./static/assets/css/output.min.css -m"
  dev:
    desc: Run go server
    cmds:
      - air .

  gen:
    desc: Start development server with hot reload
    cmds:
      - concurrently --names "templ,tailwind," --prefix "[{name}]" --prefix-colors "blue,magenta" "task templ" "task tailwind" 
