/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicianRouteImport } from './routes/technician'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsNewRouteImport } from './routes/tickets/new'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets/$ticketId'
import { Route as TicketsTicketIdEditRouteImport } from './routes/tickets/$ticketId.edit'

const TechnicianRoute = TechnicianRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsNewRoute = TicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketIdEditRoute = TicketsTicketIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TicketsTicketIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/technician': typeof TechnicianRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRouteWithChildren
  '/tickets/new': typeof TicketsNewRoute
  '/tickets/$ticketId/edit': typeof TicketsTicketIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/technician': typeof TechnicianRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRouteWithChildren
  '/tickets/new': typeof TicketsNewRoute
  '/tickets/$ticketId/edit': typeof TicketsTicketIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/technician': typeof TechnicianRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRouteWithChildren
  '/tickets/new': typeof TicketsNewRoute
  '/tickets/$ticketId/edit': typeof TicketsTicketIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/technician'
    | '/tickets/$ticketId'
    | '/tickets/new'
    | '/tickets/$ticketId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/technician'
    | '/tickets/$ticketId'
    | '/tickets/new'
    | '/tickets/$ticketId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/technician'
    | '/tickets/$ticketId'
    | '/tickets/new'
    | '/tickets/$ticketId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  TechnicianRoute: typeof TechnicianRoute
  TicketsTicketIdRoute: typeof TicketsTicketIdRouteWithChildren
  TicketsNewRoute: typeof TicketsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technician': {
      id: '/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof TechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/new': {
      id: '/tickets/new'
      path: '/tickets/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof TicketsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketId/edit': {
      id: '/tickets/$ticketId/edit'
      path: '/edit'
      fullPath: '/tickets/$ticketId/edit'
      preLoaderRoute: typeof TicketsTicketIdEditRouteImport
      parentRoute: typeof TicketsTicketIdRoute
    }
  }
}

interface TicketsTicketIdRouteChildren {
  TicketsTicketIdEditRoute: typeof TicketsTicketIdEditRoute
}

const TicketsTicketIdRouteChildren: TicketsTicketIdRouteChildren = {
  TicketsTicketIdEditRoute: TicketsTicketIdEditRoute,
}

const TicketsTicketIdRouteWithChildren = TicketsTicketIdRoute._addFileChildren(
  TicketsTicketIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  TechnicianRoute: TechnicianRoute,
  TicketsTicketIdRoute: TicketsTicketIdRouteWithChildren,
  TicketsNewRoute: TicketsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
